[pytest]
DJANGO_SETTINGS_MODULE = core.settings
# Test fayllarını avtomatik tapması üçün nümunələr:
python_files = tests.py test_*.py *_tests.py
django_db_use_migrations=true
env =
    NINJA_SKIP_REGISTRY=True